# Generated by Django 4.2.7 on 2026-02-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0003_auto_20260208_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spam', models.BooleanField(default=False, verbose_name='اسپم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL, verbose_name='بلاک شده')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='بلاک کننده')),
            ],
            options={
                'verbose_name': 'بلاک',
                'verbose_name_plural': 'بلاک\u200cها',
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='message_blo_blocker_a018f5_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
