# Generated by Django 4.2.7 on 2026-02-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteteam',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='inviteteam',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='inviteteam',
            name='team',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Leader',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='team',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='InviteTeam',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
