# Generated by Django 4.2.7 on 2026-02-08 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTP ها',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(help_text='نام فارسی رنک (مثلاً برنزی، نقره\u200cای، گلد)', max_length=100)),
                ('name_en', models.CharField(help_text='نام انگلیسی رنک (مثلاً Bronze, Silver, Gold)', max_length=100)),
                ('min_score', models.PositiveIntegerField(help_text='حداقل امتیاز برای این رنک (شامل می\u200cشود)')),
                ('max_score', models.PositiveIntegerField(help_text='حداکثر امتیاز برای این رنک (شامل می\u200cشود)')),
                ('image', models.ImageField(blank=True, help_text='آیکون/عکس این رنک', null=True, upload_to='Media/ranks')),
            ],
            options={
                'verbose_name': 'رنک',
                'verbose_name_plural': 'رنک\u200cها',
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('championships', models.IntegerField(default=0)),
                ('avatar', models.ImageField(upload_to='Media/Profile/TeamAvatar')),
                ('is_solo', models.BooleanField(default=False, help_text='تیم یک نفره مخفی برای مسابقات انفرادی (در لیست\u200cهای معمولی نمایش داده نمی\u200cشود)')),
                ('Leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز به ولت'), ('withdraw', 'برداشت از ولت'), ('comp_fee', 'هزینه ثبت\u200cنام تورنمنت'), ('comp_prize', 'جایزه تورنمنت')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='مبلغ تراکنش (به تومان)')),
                ('wallet_before', models.PositiveIntegerField(help_text='موجودی قبل از تراکنش')),
                ('wallet_after', models.PositiveIntegerField(help_text='موجودی بعد از تراکنش')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, help_text='اطلاعات اضافی به صورت JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, help_text='تیمی که در مسابقه شرکت کرده است (در صورت وجود)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='acoount.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('profile_image', models.ImageField(default='DefaultUser.webp', upload_to='Media/profile')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True)),
                ('iban', models.CharField(blank=True, help_text='شماره شبا بدون IR', max_length=26, null=True)),
                ('rank_score', models.PositiveIntegerField(default=0, help_text='امتیاز رنک (برای محاسبه رتبه)')),
                ('rank', models.ForeignKey(blank=True, help_text='سطح رنک کاربر که از بین مدل Rank انتخاب می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='acoount.rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InviteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unseen', 'دیده نشده'), ('seen', 'دیده شد'), ('responded', 'پاسخ داده شده')], default='unseen', max_length=10)),
                ('result', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_team_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_team_sender', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_team_name', to='acoount.team')),
            ],
            options={
                'verbose_name': 'دعوت تیم',
                'verbose_name_plural': 'دعوت\u200cهای تیم',
            },
        ),
    ]
