# Generated by Django 4.2.7 on 2026-02-08 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import message.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('is_private', models.BooleanField(default=True, verbose_name='خصوصی')),
                ('privacy', models.CharField(choices=[('private', 'خصوصی'), ('public', 'عمومی')], default='private', max_length=10, verbose_name='نوع پیام')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('read', 'خوانده شده'), ('archived', 'آرشیو شده'), ('deleted', 'حذف شده')], default='sent', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('attachment', models.FileField(blank=True, help_text='حداکثر حجم فایل: 10 مگابایت', null=True, upload_to=message.models.message_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar'])], verbose_name='فایل ضمیمه')),
                ('is_starred', models.BooleanField(default=False, verbose_name='ستاره\u200cدار')),
                ('is_important', models.BooleanField(default=False, verbose_name='مهم')),
                ('is_spam', models.BooleanField(default=False, verbose_name='اسپم')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='message_mes_sender__06f06a_idx'), models.Index(fields=['receiver', '-created_at'], name='message_mes_receive_1378ae_idx'), models.Index(fields=['status', '-created_at'], name='message_mes_status_7ff1fa_idx')],
            },
        ),
    ]
