# Generated by Django 4.2.7 on 2026-02-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='privacy',
        ),
    ]
