# Generated by Django 4.2.7 on 2026-02-13 14:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پلی\u200cلیست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('members', models.ManyToManyField(blank=True, related_name='shared_playlists', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_playlists', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'پلی\u200cلیست',
                'verbose_name_plural': 'پلی\u200cلیست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آهنگ')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='خواننده')),
                ('album', models.CharField(blank=True, max_length=255, null=True, verbose_name='آلبوم')),
                ('file', models.FileField(upload_to=music.models.song_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'flac', 'm4a', 'ogg', 'aac'])], verbose_name='فایل موزیک')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL, verbose_name='آپلود کننده')),
            ],
            options={
                'verbose_name': 'آهنگ',
                'verbose_name_plural': 'آهنگ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254, verbose_name='ایمیل دعوت شونده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='دعوت شونده')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='دعوت کننده')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='music.playlist', verbose_name='پلی\u200cلیست')),
            ],
            options={
                'verbose_name': 'دعوت پلی\u200cلیست',
                'verbose_name_plural': 'دعوت\u200cهای پلی\u200cلیست',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music.song', verbose_name='آهنگ\u200cها'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='music_song_uploade_09b7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_public', '-created_at'], name='music_song_is_publ_91ab1b_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='music_song_artist_173532_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album'], name='music_song_album_05217d_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='music_song_title_8e56ff_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistinvitation',
            index=models.Index(fields=['invitee_email', 'status'], name='music_playl_invitee_b1ed5d_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistinvitation',
            index=models.Index(fields=['invitee', 'status'], name='music_playl_invitee_9ddfc3_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistinvitation',
            index=models.Index(fields=['playlist', 'status'], name='music_playl_playlis_399a85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistinvitation',
            unique_together={('playlist', 'invitee_email', 'status')},
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', '-created_at'], name='music_playl_owner_i_81ed82_idx'),
        ),
    ]
