# Generated by Django 4.2.7 on 2026-02-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaybackState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.FloatField(default=0.0, verbose_name='آخرین موقعیت (ثانیه)')),
                ('last_played_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین پخش')),
                ('last_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_states', to='music.song', verbose_name='آخرین آهنگ پخش شده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_state', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وضعیت پخش کاربر',
                'verbose_name_plural': 'وضعیت\u200cهای پخش کاربران',
                'indexes': [models.Index(fields=['user', '-last_played_at'], name='music_userp_user_id_7e3742_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='music.song', verbose_name='آهنگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_songs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آهنگ مورد علاقه',
                'verbose_name_plural': 'آهنگ\u200cهای مورد علاقه',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='music_favor_user_id_089c69_idx')],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
